# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STYLiSH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for STYLiSH
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'Alamofire', '~> 5.5'
  pod 'IQKeyboardManagerSwift'
  pod 'StatusAlert', '~> 1.1.1'


end
